apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-12T08:04:43Z"
  labels:
    app: jupyter-app
  name: jupyter-svc
  namespace: jupyter
  resourceVersion: "15527"
  uid: b22b03f5-906b-4d73-afad-86ee86b795ee
spec:
  clusterIP: 10.111.126.113
  clusterIPs:
  - 10.111.126.113
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30000
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: jupyter-pods
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}