apiVersion: v1
kind: ConfigMap
metadata:
  name: meu-cm
data:
  # Connection database configuration
  database: mysql
  database_uri: mysql://localhost:3306

  # User Interface
  font.title: Arial Bold
  background-color: red
  theme.1: clean