apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: myapp
spec:
  containers:
  - name: redis-container
    image: redis
    volumeMounts:
    - mountPath: "/my-data"
      name: "my-hostpath-volume"

  volumes:
  - name: "my-hostpath-volume"
    hostPath:
      path: "/var/lib/2-persist"